USE [master]
GO

-- CREACION BASE DE DATOS --

CREATE DATABASE [DB_ASOBAC]
GO

USE [DB_ASOBAC]
GO

CREATE SCHEMA SCH_ADMINISTRATIVO
GO

CREATE SCHEMA SCH_DIRECCIONES
GO

CREATE SCHEMA SCH_CREDITOS
GO

CREATE SCHEMA SCH_AHORROS
GO

-- TABLA DE USUARIOS --

CREATE TABLE [SCH_ADMINISTRATIVO].[USUARIOS]
(
	[USUARIOID]			VARCHAR(15)		NOT NULL,
	[CEDULA]			VARCHAR(10)		NOT NULL,
	[ESTADOID]			TINYINT			NOT NULL,
	[ROLID]				TINYINT			NOT NULL,
	[PRIMERNOMBRE]		VARCHAR(30)		NOT NULL,
	[SEGUNDONOMBRE]		VARCHAR(30)		NULL,
	[PRIMERAPELLIDO]	VARCHAR(30)		NOT NULL,
	[SEGUNDOAPELLIDO]	VARCHAR(30)		NOT NULL,
	[EMAIL]				VARCHAR(100)	NOT NULL,
	[CLAVE]				VARCHAR(40)		NOT NULL,
	[BLOGIN]			BIT				NULL,
	[INTENTOS]			TINYINT			NOT NULL,

	CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED
	(
		[USUARIOID]	ASC
	)
)
GO

-- TABLA DE ROLES --

CREATE TABLE [SCH_ADMINISTRATIVO].[ROLES]
(
	[ROLID]				TINYINT			NOT NULL	IDENTITY(1,1),
	[DESC_ROL]			VARCHAR(50)		NOT NULL,

	CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED
	(
		[ROLID]	ASC
	)
)
GO

-- TABLA DE ESTADOS --

CREATE TABLE [SCH_ADMINISTRATIVO].[ESTADOS]
(
	[ESTADOID]			TINYINT			NOT NULL	IDENTITY(1,1),
	[DESC_ESTADO]		VARCHAR(25)		NOT NULL,

	CONSTRAINT [PK_ESTADOS] PRIMARY KEY CLUSTERED
	(
		[ESTADOID] ASC
	)
)
GO
   
-- TABLA DE TELEFONOS -- 

CREATE TABLE [SCH_ADMINISTRATIVO].[TELEFONOS]
(
	[TELEFONOID]		INT				NOT NULL,
	[USUARIOID]			VARCHAR(15)		NOT NULL,
	[NUMERO]			VARCHAR(10)		NOT NULL,
	[DESC_TELEFONO]		VARCHAR (100)	NULL,
	
	CONSTRAINT [PK_TELEFONOS] PRIMARY KEY CLUSTERED
	(
		[TELEFONOID] ASC
	)
)
GO

-- TABLA DE DIRECCIONES --

CREATE TABLE [SCH_DIRECCIONES].[DIRECCIONES]
(
	[DIRECCIONID]		INT				NOT NULL	IDENTITY(1,1),
	[USUARIOID]			VARCHAR(15)		NOT NULL,
	[DISTRITOID]		SMALLINT		NOT NULL,
	[OTRAS_SENAS]		VARCHAR(150)	NOT NULL,

	CONSTRAINT [PK_DIRECCIONES] PRIMARY KEY CLUSTERED
	(
		[DIRECCIONID] ASC
	)
)
GO

-- TABLA DE DISTRITOS --

CREATE TABLE [SCH_DIRECCIONES].[DISTRITOS]
(
	[DISTRITOID]		SMALLINT		NOT NULL,
	[CANTONID]			SMALLINT		NOT NULL,
	[NOMDISTRITO]		VARCHAR(20)		NOT NULL,

	CONSTRAINT [PK_DISTRITOS] PRIMARY KEY CLUSTERED
	(
		[DISTRITOID] ASC
	)
)
GO

-- TABLA DE CANTONES --

CREATE TABLE [SCH_DIRECCIONES].[CANTONES]
(
	[CANTONID]			SMALLINT		NOT NULL,
	[PROVINCIAID]		SMALLINT		NOT NULL,
	[NOMCANTON]			VARCHAR(20)		NOT NULL,

	CONSTRAINT [PK_CANTONES] PRIMARY KEY CLUSTERED
	(
		[CANTONID] ASC
	)
)
GO

-- TABLA DE PROVINCIAS --

CREATE TABLE [SCH_DIRECCIONES].[PROVINCIAS]
(
	[PROVINCIAID]		SMALLINT		NOT NULL,
	[NOMPROVINCIA]		VARCHAR(20)		NOT NULL,

	CONSTRAINT [PK_PROVINCIAS] PRIMARY KEY CLUSTERED
	(
		[PROVINCIAID] ASC
	)
)
GO

-- TABLA DE ASOCIADOS --

CREATE TABLE [SCH_ADMINISTRATIVO].[ASOCIADOS]
(
	[USUARIOID]			VARCHAR(15)		NOT NULL,
	[FECHA_AFILIACION]	DATE			NOT NULL,

	CONSTRAINT [PK_ASOCIADOS] PRIMARY KEY CLUSTERED
	(
		[USUARIOID] ASC
	)
)
GO

CREATE TABLE [SCH_ADMINISTRATIVO].[CUENTAS_BANCARIAS]
(
	[CUENTAID]			INT				NOT NULL	IDENTITY(1,1),
	[USUARIOID]			VARCHAR(15)		NOT NULL,
	[NOMBRE_BANCO]		VARCHAR(30)		NOT NULL,
	[TIPOCUENTA]		VARCHAR(15)		NOT NULL,
	[MONEDA]			TINYINT			NOT NULL,

	CONSTRAINT [PK_CUENTAS_BANCARIAS] PRIMARY KEY CLUSTERED
	(
		[CUENTAID] ASC
	)

)
GO

 -- TABLA DE CREDITOS --

 CREATE TABLE [SCH_CREDITOS].[CREDITOS]
 (
	[CREDITOID]			INT				NOT NULL	IDENTITY(1,1),
	[USUARIOID]			VARCHAR(15)		NOT NULL,
	[TIPOCREDITOID]		SMALLINT		NOT NULL,
	[ESTCREDITOID]		TINYINT			NOT NULL,
	[FEC_INICIO]		DATE			NOT NULL,
	[PLAZO]				SMALLINT		NOT NULL,
	[MONTO_CREDITO]		MONEY			NOT NULL,
	[CUOTAS_PAGADAS]	SMALLINT		NOT NULL,
	[CUOTAS_RESTANTES]	SMALLINT		NOT NULL,
	[DESC_CREDITO]		VARCHAR(100)	NOT NULL,

	CONSTRAINT [PK_CREDITOS] PRIMARY KEY CLUSTERED
	(
		[CREDITOID] ASC
	)
 )
 GO

 -- TABLA DE TIPOS DE CREDITO --

 CREATE TABLE [SCH_CREDITOS].[CREDITOS_TIPOS]
 (
	[TIPOCREDITOID]		SMALLINT		NOT NULL	IDENTITY(1,1),
	[ESTADOID]			TINYINT			NOT NULL,
	[TASAINTERES]		TINYINT			NOT NULL,
	[PLAZO_MIN]			SMALLINT		NOT NULL,
	[PLAZO_MAX]			SMALLINT		NOT NULL,
	[DESC_TIPO]			VARCHAR(50)		NOT NULL,

	CONSTRAINT [PK_CREDITOS_TIPOS] PRIMARY KEY CLUSTERED
	(
		[TIPOCREDITOID] ASC
	)
 )
 GO

 -- TABLA DE ESTADOS DE CREDITO --

 CREATE TABLE [SCH_CREDITOS].[CREDITOS_ESTADOS]
 (
	[ESTCREDITOID]		TINYINT			NOT NULL	IDENTITY(1,1),
	[DESC_ESTADO]		VARCHAR(50)		NOT NULL,

	CONSTRAINT [PK_CREDITOS_ESTADOS] PRIMARY KEY CLUSTERED
	(
		[ESTCREDITOID] ASC
	)
 )
 GO

 -- TABLA DE HISTORIAL DE CREDITOS --

 CREATE TABLE [SCH_CREDITOS].[CREDITOS_HISTORIAL]
 (
	[HISTCREDITOID]		INT				NOT NULL	IDENTITY(1,1),
	[CREDITOID]			INT				NOT NULL,
	[CUOTA]				MONEY			NOT NULL,
	[INTERES_PAGADO]	MONEY			NOT NULL,
	[AMORTIZADO]		MONEY			NOT NULL,
	[SALDO]				MONEY			NOT NULL,
	[FEC_MOVIMIENTO]	DATETIME		NOT NULL,

	CONSTRAINT [PK_CREDITOS_HISTORIAL] PRIMARY KEY CLUSTERED
	(
		[HISTCREDITOID] ASC
	)
 )
 GO

 -- TABLA DE CONDICIONES PARA CREDITO --

 CREATE TABLE [SCH_CREDITOS].[CREDITOS_CONDICIONES]
 (
	[CONDICIONID]		SMALLINT		NOT NULL	IDENTITY(1,1),
	[TIPOCREDITOID]		SMALLINT		NOT NULL,
	[DESC_CONDICION]	VARCHAR(100)	NOT NULL,

	CONSTRAINT [PK_CREDITOS_CONDICIONES] PRIMARY KEY CLUSTERED
	(
		[CONDICIONID] ASC
	)
 )
 GO

 -- TABLA DE AHORROS --

 CREATE TABLE [SCH_AHORROS].[AHORROS]
 (
	[AHORROID]			INT				NOT NULL	IDENTITY(1,1),
	[USUARIOID]			VARCHAR(15)		NOT NULL,
	[TIPOAHORROID]		SMALLINT		NOT NULL,
	[FEC_INICIO]		DATE			NOT NULL,
	[FEC_FINAL]			DATE			NOT NULL,
	[DESC_AHORRO]		VARCHAR(100)	NOT NULL,

	CONSTRAINT [PK_AHORROS] PRIMARY KEY CLUSTERED
	(
		[AHORROID] ASC
	)
 )
 GO

 -- TIPOS DE AHORRO --

 CREATE TABLE [SCH_AHORROS].[AHORROS_TIPOS]
 (
	 [TIPOAHORROID]		SMALLINT		NOT NULL	IDENTITY(1,1),
	 [ESTADOID]			TINYINT			NOT NULL,
	 [PORCENTAJEOMONTO]	BIT				NOT NULL,
	 [RETIRO_EXTRA]		BIT				NOT NULL,
	 [PENALIZACION]		BIT				NOT NULL,
	 [PLAZO]			SMALLINT		NOT NULL,
	 [PORCENTAJE]		TINYINT			NOT NULL,
	 [DESC_TIPO]		VARCHAR(50)		NOT NULL,

	 CONSTRAINT [PK_AHORROS_TIPOS] PRIMARY KEY CLUSTERED
	 (
		[TIPOAHORROID] ASC
	 )
 )
 GO

 -- TABLA DE HISTORIAL DE AHORROS --

 CREATE TABLE [SCH_AHORROS].[AHORROS_HISTORIAL]
 (
	[HISTAHORROID]		INT				NOT NULL	IDENTITY(1,1),
	[AHORROID]			INT				NOT NULL,
	[MONTO_AHORRO]		MONEY			NOT NULL,
	[TOTAL_AHORRADO]	MONEY			NOT NULL,
	[FEC_MOVIMIENTO]	DATETIME		NOT NULL,

	CONSTRAINT [PK_AHORROS_HISTORIAL] PRIMARY KEY CLUSTERED
	(
		[HISTAHORROID] ASC
	)
 )
 GO

---------------------------------RELACIONES ENTRE TABLAS---------------------------------

-- FK TABLA USUARIOS

--USUARIOS A ESTADO
ALTER TABLE [SCH_ADMINISTRATIVO].[USUARIOS] WITH NOCHECK
	ADD CONSTRAINT [FK_USUARIOS_ESTADOS] FOREIGN KEY ([ESTADOID])
	REFERENCES [SCH_ADMINISTRATIVO].[ESTADOS]([ESTADOID])
GO

ALTER TABLE [SCH_ADMINISTRATIVO].[USUARIOS] CHECK CONSTRAINT [FK_USUARIOS_ESTADOS]
GO

--USUARIOS A ROLES
ALTER TABLE [SCH_ADMINISTRATIVO].[USUARIOS] WITH NOCHECK
	ADD CONSTRAINT [FK_USUARIOS_ROLES] FOREIGN KEY ([ROLID])
	REFERENCES [SCH_ADMINISTRATIVO].[ROLES]([ROLID])
GO

ALTER TABLE [SCH_ADMINISTRATIVO].[USUARIOS] CHECK CONSTRAINT [FK_USUARIOS_ROLES]
GO

-- FK TABLA TELEFONOS

ALTER TABLE [SCH_ADMINISTRATIVO].[TELEFONOS] WITH NOCHECK
	ADD CONSTRAINT [FK_TELEFONOS_USUARIOS] FOREIGN KEY ([USUARIOID])
	REFERENCES [SCH_ADMINISTRATIVO].[USUARIOS]([USUARIOID])
GO

ALTER TABLE [SCH_ADMINISTRATIVO].[TELEFONOS] CHECK CONSTRAINT [FK_TELEFONOS_USUARIOS]
GO

-- FK TABLA DIRECCIONES

-- DIRECCIONES A SUS USUARIOS
ALTER TABLE [SCH_DIRECCIONES].[DIRECCIONES] WITH NOCHECK
	ADD CONSTRAINT [FK_DIRECCIONES_USUARIOS] FOREIGN KEY ([USUARIOID])
	REFERENCES [SCH_ADMINISTRATIVO].[USUARIOS]([USUARIOID])
GO

ALTER TABLE [SCH_DIRECCIONES].[DIRECCIONES] CHECK CONSTRAINT [FK_DIRECCIONES_USUARIOS]
GO

-- DIRECCION A SU DISTRITO
ALTER TABLE [SCH_DIRECCIONES].[DIRECCIONES] WITH NOCHECK
	ADD CONSTRAINT [FK_DIRECCIONES_DISTRITOS] FOREIGN KEY ([DISTRITOID])
	REFERENCES [SCH_DIRECCIONES].[DISTRITOS]([DISTRITOID])
GO

ALTER TABLE [SCH_DIRECCIONES].[DIRECCIONES] CHECK CONSTRAINT [FK_DIRECCIONES_DISTRITOS]
GO

-- FK TABLA DISTRITOS

ALTER TABLE [SCH_DIRECCIONES].[DISTRITOS] WITH NOCHECK
	ADD CONSTRAINT [FK_DISTRITOS_CANTONES] FOREIGN KEY ([CANTONID])
	REFERENCES [SCH_DIRECCIONES].[CANTONES]([CANTONID])
GO

ALTER TABLE [SCH_DIRECCIONES].[DISTRITOS] CHECK CONSTRAINT [FK_DISTRITOS_CANTONES]
GO

-- FK TABLA CANTONES

ALTER TABLE [SCH_DIRECCIONES].[CANTONES] WITH NOCHECK
	ADD CONSTRAINT [FK_CANTONES_PROVINCIAS] FOREIGN KEY ([PROVINCIAID])
	REFERENCES [SCH_DIRECCIONES].[PROVINCIAS]([PROVINCIAID])
GO

ALTER TABLE [SCH_DIRECCIONES].[CANTONES] CHECK CONSTRAINT [FK_CANTONES_PROVINCIAS]
GO

-- FK TABLA ASOCIADOS

-- ASOCIADOS A USUARIOS
ALTER TABLE [SCH_ADMINISTRATIVO].[ASOCIADOS] WITH NOCHECK
	ADD CONSTRAINT [FK_ASOCIADOS_USUARIOS] FOREIGN KEY ([USUARIOID])
	REFERENCES [SCH_ADMINISTRATIVO].[USUARIOS]([USUARIOID])
GO

ALTER TABLE [SCH_ADMINISTRATIVO].[ASOCIADOS] CHECK CONSTRAINT [FK_ASOCIADOS_USUARIOS]
GO

-- FK TABLA CUENTAS_BANCARIAS

-- CUENTAS BANCARIAS A USUARIOS

ALTER TABLE [SCH_ADMINISTRATIVO].[CUENTAS_BANCARIAS] WITH NOCHECK
	ADD CONSTRAINT [FK_CUENTAS_BANCARIAS_USUARIOS] FOREIGN KEY ([USUARIOID])
	REFERENCES [SCH_ADMINISTRATIVO].[USUARIOS]([USUARIOID])
GO

ALTER TABLE [SCH_ADMINISTRATIVO].[CUENTAS_BANCARIAS] CHECK CONSTRAINT [FK_CUENTAS_BANCARIAS_USUARIOS]
GO

-- FK TABLA CREDITOS

-- CREDITOS A SUS USUARIOS
ALTER TABLE [SCH_CREDITOS].[CREDITOS] WITH NOCHECK
	ADD CONSTRAINT [FK_CREDITOS_USUARIOS] FOREIGN KEY ([USUARIOID])
	REFERENCES [SCH_ADMINISTRATIVO].[USUARIOS]([USUARIOID])
GO

ALTER TABLE [SCH_CREDITOS].[CREDITOS] CHECK CONSTRAINT [FK_CREDITOS_USUARIOS]
GO

-- CREDITOS A SU TIPO DE CREDITO
ALTER TABLE [SCH_CREDITOS].[CREDITOS] WITH NOCHECK
	ADD CONSTRAINT [FK_CREDITOS_CREDITOS_TIPOS] FOREIGN KEY ([TIPOCREDITOID])
	REFERENCES [SCH_CREDITOS].[CREDITOS_TIPOS]([TIPOCREDITOID])
GO

ALTER TABLE [SCH_CREDITOS].[CREDITOS] CHECK CONSTRAINT [FK_CREDITOS_CREDITOS_TIPOS]
GO

-- CREDITOS A SU ESTADO DE APROBACION
ALTER TABLE [SCH_CREDITOS].[CREDITOS] WITH NOCHECK
	ADD CONSTRAINT [FK_CREDITOS_CREDITOS_ESTADOS] FOREIGN KEY ([ESTCREDITOID])
	REFERENCES [SCH_CREDITOS].[CREDITOS_ESTADOS]([ESTCREDITOID])
GO

ALTER TABLE [SCH_CREDITOS].[CREDITOS] CHECK CONSTRAINT [FK_CREDITOS_CREDITOS_ESTADOS]
GO

-- FK TABLA CREDITOS TIPOS

-- TIPOS DE CREDITO CON SU ESTADO
ALTER TABLE [SCH_CREDITOS].[CREDITOS_TIPOS] WITH NOCHECK
	ADD CONSTRAINT [FK_CREDITOS_TIPOS_ESTADOS] FOREIGN KEY ([ESTADOID])
	REFERENCES [SCH_ADMINISTRATIVO].[ESTADOS]([ESTADOID])
GO

ALTER TABLE [SCH_CREDITOS].[CREDITOS_TIPOS] CHECK CONSTRAINT [FK_CREDITOS_TIPOS_ESTADOS]
GO

-- FK TABLA CONDICIONES

ALTER TABLE [SCH_CREDITOS].[CREDITOS_CONDICIONES] WITH NOCHECK
	ADD CONSTRAINT [FK_CREDITOS_CONDICIONES_CREDITOS_TIPOS] FOREIGN KEY ([TIPOCREDITOID])
	REFERENCES [SCH_CREDITOS].[CREDITOS_TIPOS]([TIPOCREDITOID])
GO

ALTER TABLE [SCH_CREDITOS].[CREDITOS_CONDICIONES] CHECK CONSTRAINT [FK_CREDITOS_CONDICIONES_CREDITOS_TIPOS]
GO

-- FK TABLA HISTORIAL DE CREDITOS

ALTER TABLE [SCH_CREDITOS].[CREDITOS_HISTORIAL] WITH NOCHECK
	ADD CONSTRAINT [FK_CREDITOS_HISTORIAL__CREDITOS] FOREIGN KEY ([CREDITOID])
	REFERENCES [SCH_CREDITOS].[CREDITOS]([CREDITOID])
GO

ALTER TABLE [SCH_CREDITOS].[CREDITOS_HISTORIAL] CHECK CONSTRAINT [FK_CREDITOS_HISTORIAL__CREDITOS]
GO

-- FK TABLA AHORROS

-- AHORROS A SUS USUARIOS
ALTER TABLE [SCH_AHORROS].[AHORROS] WITH NOCHECK
	ADD CONSTRAINT [FK_AHORROS_USUARIOS] FOREIGN KEY ([USUARIOID])
	REFERENCES [SCH_ADMINISTRATIVO].[USUARIOS]([USUARIOID])
GO

ALTER TABLE [SCH_AHORROS].[AHORROS] CHECK CONSTRAINT [FK_AHORROS_USUARIOS]
GO

-- AHORROS A SU TIPO DE AHORROS
ALTER TABLE [SCH_AHORROS].[AHORROS] WITH NOCHECK
	ADD CONSTRAINT [FK_AHORROS_AHORROS_TIPOS] FOREIGN KEY ([TIPOAHORROID])
	REFERENCES [SCH_AHORROS].[AHORROS_TIPOS]([TIPOAHORROID])
GO

ALTER TABLE [SCH_AHORROS].[AHORROS] CHECK CONSTRAINT [FK_AHORROS_AHORROS_TIPOS]
GO

-- FK TABLA AHORROS TIPOS

-- TIPOS DE AHORROS CON SU ESTADO
ALTER TABLE [SCH_AHORROS].[AHORROS_TIPOS] WITH NOCHECK
	ADD CONSTRAINT [FK_AHORROS_TIPOS_ESTADOS] FOREIGN KEY ([ESTADOID])
	REFERENCES [SCH_ADMINISTRATIVO].[ESTADOS]([ESTADOID])
GO 

ALTER TABLE [SCH_AHORROS].[AHORROS_TIPOS] CHECK CONSTRAINT [FK_AHORROS_TIPOS_ESTADOS]
GO

-- FK TABLA HISTORIAL DE CREDITOS

ALTER TABLE [SCH_AHORROS].[AHORROS_HISTORIAL] WITH NOCHECK
	ADD CONSTRAINT [FK_AHORROS_HISTORIAL__AHORROS] FOREIGN KEY ([AHORROID])
	REFERENCES [SCH_AHORROS].[AHORROS]([AHORROID])
GO

ALTER TABLE [SCH_AHORROS].[AHORROS_HISTORIAL] CHECK CONSTRAINT [FK_AHORROS_HISTORIAL__AHORROS]
GO
