USE [DB_ASOBAC]
GO

INSERT INTO [SCH_ADMINISTRATIVO].[ROLES]
	VALUES
		('IT'),
		('ADMIN_JUNT'),
		('ADMIN_ASOC'),
		('ASOCIADO')
GO

INSERT INTO [SCH_ADMINISTRATIVO].[ESTADOS]
	VALUES
		('ACTIVO'),
		('INACTIVO')
GO

INSERT INTO [SCH_ADMINISTRATIVO].[USUARIOS]
	VALUES
		('admin', '116130484', 1, 1, 'David', 'Josué', 'Díaz', 'Aguilar', 'nanosama95@gmail.com', '1234', 1, 0)
GO

INSERT INTO [SCH_ADMINISTRATIVO].[ASOCIADOS]
	VALUES
		('admin', '1/04/2022')
GO


--DELETE FROM [SCH_ADMINISTRATIVO].ASOCIADOS WHERE USUARIOID = 'admin2'
--DELETE FROM [SCH_ADMINISTRATIVO].USUARIOS where USUARIOID = 'admin2'


--cuenta
--asobac88@outlook.com
--pass outlook @soBAC882022
