USE [DB_ASOBAC]
GO

CREATE FUNCTION [SCH_ADMINISTRATIVO].[FN_LOGIN]
(
	@Usuario		VARCHAR(15),
	@Contrasenha	VARCHAR(40)
)
RETURNS INTEGER
AS
	BEGIN
		DECLARE @cantidad INTEGER
	
		SELECT @cantidad = COUNT(USU.USUARIOID)
		FROM [SCH_ADMINISTRATIVO].[USUARIOS] USU
			LEFT OUTER JOIN [SCH_ADMINISTRATIVO].[ASOCIADOS] ASO
				ON USU.USUARIOID = ASO.USUARIOID
				WHERE USU.USUARIOID = @Usuario AND USU.CLAVE = @Contrasenha

		IF (@cantidad = 1)
			SELECT @cantidad += USU.BLOGIN FROM [SCH_ADMINISTRATIVO].[USUARIOS] USU WHERE USU.USUARIOID = @Usuario
		ELSE
			SELECT @cantidad = 0

		RETURN(@cantidad)
	END
GO

CREATE PROCEDURE [SCH_ADMINISTRATIVO].[SP_LOGIN]
(
	@Usuario		VARCHAR(15),
	@Contrasenha	VARCHAR(40)
)
AS
	BEGIN
		SELECT [SCH_ADMINISTRATIVO].[FN_LOGIN](@Usuario, @Contrasenha)
	END
GO

CREATE PROCEDURE [SCH_ADMINISTRATIVO].[SP_BUSCAR_CORREO]
(
	@email			varchar(150)
)
AS
	BEGIN
		SELECT COUNT(USU.EMAIL)
		FROM [SCH_ADMINISTRATIVO].[USUARIOS] USU
		WHERE LTRIM(RTRIM([USU].EMAIL)) LIKE '%' + RTRIM(LTRIM(@email)) + '%'
	END
GO

-- EXEC [SCH_ADMINISTRATIVO].[SP_BUSCAR_CORREO] 'nanosama95@gmail.com'

-- UPDATE [SCH_ADMINISTRATIVO].USUARIOS SET BLOGIN = 1 WHERE USUARIOID = 'admin'